### PR TITLE
Adding removal of exile bed spawn on combat death

### PR DESCRIPTION
**Pull request by Diet-Cola**
If an exile player dies by a killer, then this new rule will remove their bed spawn and force a random spawn. Probably needs a test and also committing to 1.14 branch

### CODE REVIEW

**Comment by Diet-Cola** [comment]
Apologies for the bunch of commits, I've forgot my user and pw for git so I couldnt properly do it 😅

**Comment by dquist** [comment]
Damn, you fellas are still going at this?

**Comment by Diet-Cola** [comment]
No other way to justify playing minecraft 😅

**Comment by Maxopoly** [comment]
This PR does not do what it intends to do and likely should not have been merged. It only resets the exiles bed location when he is pearled for the first time, not when he is killed again while exiled. The method returns in line 547 if the player is exiled, that's where the bed reset should be.

**Comment by Maxopoly** [comment]
Additionally actual non-repeating commit messages would be welcome, at least for feature oriented PRs

**Pull request merged**
