### PR TITLE
Clean up the config

### PR DESCRIPTION
**Pull request by iykHvfIvfR**
Not tested.

I love trailing whitespace.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
would prefer tested before merge, and would need a version update or _something_ to warn people that the configs won't be cross compatible.

**Comment by iykHvfIvfR** [comment]
How about supporting both configs for a couple of releases while showing deprecation warnings?

**Comment by ProgrammerDan** [comment]
that'd work -- just needs to be a big label warning :)

**Comment by danquist** [comment]
I admire your effort to clean up the config, but there's a reason why I put all the config comments in one block at the top.

Config comments aren't parsed by the yaml parser, so if you interlace comments and settings, most of the comments will be deleted if you ever update a settings from console triggering a re-save of the config.

snakeyaml is at least smart enough to keep any existing comments at the top of a file when saving. Any comments before the first setting will be preserved, while any other comments will be removed.

I will add there could be a way of preserving the interlaced comments that I'm not aware of, I was just never able to figure out a way to do it. It's easy enough to test, just run the plugin, change a value with `ep config set` and then `ep config save` from console. Observe the resulting saved file.

**Comment by iykHvfIvfR** [comment]
>most of the comments will be deleted if you ever update a settings from console

The purpose of which is?

I don't see any benefits over simply editing the config file itself. If you want dynamic reloading either periodically check if the config file has changed or add a /config_reload command.

**Comment by ProgrammerDan** [comment]
It's a pretty big feature class to have live editing of configs in a minecraft mod. Surprisingly difficult to do right.

**Comment by danquist** [comment]
There actually is a config reload command.

And I don't entirely remember the reason for changing settings through console, but @ProgrammerDan may have specifically requested it. 

>Surprisingly difficult to do right.

Did I do it right??

**Comment by ProgrammerDan** [comment]
Does it work? You did it right :P

**Comment by ProgrammerDan** [comment]
@iykHvfIvfR Do you intent to modify or alter approach based on comments here? Or, something else?

**Comment by iykHvfIvfR** [comment]
@ProgrammerDan Oh yea, I'm just being slow. I'm gonna remove whatever functionality is responsible for editing the config file and make my changes backward-compatible.

**Comment by ProgrammerDan** [comment]
No worries, thanks for the update.

**Pull request closed without merging**
